// Standalone scene player — runs inside the exported HTML page, with no
// dependency on the rest of the app. Plain JS (not type-checked, not built
// by Vite): its source is embedded verbatim into the export by
// exportStandalonePage.ts, so what ships is exactly what's on disk here.
// `THREE`/`OrbitControls` come off the prebuilt vendor IIFE (see
// player/vendor/vendor.js, regenerated by `npm run build:player-vendor`)
// rather than an ES import: three's own module build imports internally
// from a sibling './three.core.js' by relative URL, which a data-URI
// import map can't resolve (no hierarchical base to resolve against) — the
// vendor bundle is Rollup flattening that whole graph ahead of time so
// nothing here needs module resolution at all.
const THREE = window.OVMVendor.THREE;
const OrbitControls = window.OVMVendor.OrbitControls;

const TYPED_ARRAY_CTORS = {
  Float32Array,
  Uint32Array,
  Uint16Array,
  Uint8Array,
};

function base64ToUint8(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function decodeAttribute(attr) {
  const Ctor = TYPED_ARRAY_CTORS[attr.type] || Float32Array;
  const bytes = base64ToUint8(attr.base64);
  const array = new Ctor(bytes.buffer, bytes.byteOffset, bytes.byteLength / Ctor.BYTES_PER_ELEMENT);
  return new THREE.BufferAttribute(array, attr.itemSize);
}

function buildGeometry(snap) {
  const geometry = new THREE.BufferGeometry();
  for (const name of ["position", "normal", "color", "uv"]) {
    const attr = snap.attributes[name];
    if (attr) geometry.setAttribute(name, decodeAttribute(attr));
  }
  if (snap.index) geometry.setIndex(decodeAttribute(snap.index));
  if (!snap.attributes.normal && snap.attributes.position) geometry.computeVertexNormals();
  if (snap.groups) {
    geometry.clearGroups();
    for (const g of snap.groups) geometry.addGroup(g.start, g.count, g.materialIndex);
  }
  geometry.computeBoundingSphere();
  return geometry;
}

function buildMaterial(snap, kind) {
  const hasVertexColor = Boolean(snap && snap.vertexColors);
  if (kind === "points") {
    return new THREE.PointsMaterial({
      color: snap?.color ?? 0xffffff,
      size: snap?.size ?? 0.02,
      sizeAttenuation: snap?.sizeAttenuation ?? true,
      vertexColors: hasVertexColor,
    });
  }
  if (kind === "line" || kind === "linesegments") {
    return new THREE.LineBasicMaterial({ color: snap?.color ?? 0xffffff, vertexColors: hasVertexColor });
  }
  const material = new THREE.MeshStandardMaterial({
    color: snap?.color ?? 0xffffff,
    emissive: snap?.emissive ?? 0x000000,
    emissiveIntensity: snap?.emissiveIntensity ?? 1,
    roughness: snap?.roughness ?? 0.5,
    metalness: snap?.metalness ?? 0.1,
    opacity: snap?.opacity ?? 1,
    transparent: Boolean(snap?.transparent),
    wireframe: Boolean(snap?.wireframe),
    vertexColors: hasVertexColor,
    side: THREE.DoubleSide,
  });
  // Paths are relative to index.html (e.g. "textures/tex_0.png") — plain
  // <img>-style loads (what TextureLoader does internally), which is what
  // lets a folder export work by double-clicking index.html straight off
  // disk: fetch()/XHR to a sibling file is blocked on the file:// origin in
  // Chrome, but a tag-based resource load isn't.
  if (snap?.mapFile) {
    const map = new THREE.TextureLoader().load(snap.mapFile);
    map.colorSpace = THREE.SRGBColorSpace;
    material.map = map;
  }
  if (snap?.normalMapFile) {
    material.normalMap = new THREE.TextureLoader().load(snap.normalMapFile);
  }
  return material;
}

function buildLight(snap) {
  let light;
  switch (snap.kind) {
    case "ambient":
      light = new THREE.AmbientLight(snap.color, snap.intensity);
      break;
    case "directional":
      light = new THREE.DirectionalLight(snap.color, snap.intensity);
      break;
    case "point":
      light = new THREE.PointLight(snap.color, snap.intensity, snap.distance || 0);
      break;
    case "spot":
      light = new THREE.SpotLight(snap.color, snap.intensity, snap.distance || 0, snap.angle, snap.penumbra);
      break;
    default:
      return null;
  }
  return light;
}

/**
 * Recursively reconstructs a captured SnapshotNode tree into live
 * THREE.Object3D instances. `animated` collects every node that carries
 * more than one baked frame (see sceneSnapshot.ts's captureAnimatedScene) —
 * the render loop below walks that flat list once per frame instead of
 * re-traversing the whole tree, and instead of every OTHER node (an
 * un-animated static prop) paying any per-frame cost at all.
 */
function buildObject(node, scene, lightCount, animated) {
  let object;
  if (node.kind === "light") {
    const light = buildLight(node.light);
    if (!light) return null;
    if (node.light.targetPosition && light.target) {
      light.target.position.set(...node.light.targetPosition);
      scene.add(light.target);
    }
    object = light;
    lightCount.n++;
  } else if (node.kind === "points" || node.kind === "mesh" || node.kind === "line" || node.kind === "linesegments") {
    const geometry = buildGeometry(node.geometry);
    const material = node.materials ? node.materials.map((m) => buildMaterial(m, node.kind)) : buildMaterial(node.material, node.kind);
    const instances = node.geometry.instances;
    if (node.kind === "mesh" && instances) {
      const mesh = new THREE.InstancedMesh(geometry, material, instances.count);
      mesh.instanceMatrix = decodeAttribute(instances.matrices);
      mesh.instanceMatrix.needsUpdate = true;
      if (instances.colors) {
        mesh.instanceColor = decodeAttribute(instances.colors);
        mesh.instanceColor.needsUpdate = true;
      }
      object = mesh;
    } else {
      object =
        node.kind === "points"
          ? new THREE.Points(geometry, material)
          : node.kind === "line"
            ? new THREE.Line(geometry, material)
            : node.kind === "linesegments"
              ? new THREE.LineSegments(geometry, material)
              : new THREE.Mesh(geometry, material);
    }
  } else {
    object = new THREE.Group();
  }

  object.matrixAutoUpdate = false;
  object.matrix.fromArray(node.matrix);
  object.visible = node.visible;
  object.name = node.name || "";
  if (node.frames && node.frames.length > 1) animated.push({ object, frames: node.frames });

  for (const child of node.children || []) {
    const built = buildObject(child, scene, lightCount, animated);
    if (built) object.add(built);
  }
  return object;
}

function fitCameraToObject(camera, controls, object) {
  const box = new THREE.Box3().setFromObject(object);
  if (box.isEmpty()) {
    camera.position.set(5, 5, 5);
    controls.target.set(0, 0, 0);
    return;
  }
  const sphere = box.getBoundingSphere(new THREE.Sphere());
  const distance = Math.max(sphere.radius * 2.2, 0.5);
  camera.near = Math.max(distance / 1000, 0.001);
  camera.far = distance * 100;
  camera.position.copy(sphere.center).add(new THREE.Vector3(distance, distance * 0.6, distance));
  camera.updateProjectionMatrix();
  controls.target.copy(sphere.center);
}

export function runPlayer(sceneData, container) {
  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x14161a);

  const lightCount = { n: 0 };
  const animated = [];
  const root = buildObject(sceneData, scene, lightCount, animated);
  scene.add(root);

  // Nothing exported carried a light — a MeshStandardMaterial mesh would
  // otherwise render pure black (a captured Points cloud stays fine either
  // way, since PointsMaterial is unlit and reads vertex colors directly).
  if (lightCount.n === 0) {
    scene.add(new THREE.AmbientLight(0xffffff, 0.7));
    const sun = new THREE.DirectionalLight(0xffffff, 1.1);
    sun.position.set(5, 10, 7);
    scene.add(sun);
  }

  const camera = new THREE.PerspectiveCamera(50, container.clientWidth / container.clientHeight, 0.1, 1000);
  const renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setSize(container.clientWidth, container.clientHeight);
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  container.appendChild(renderer.domElement);

  const controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;

  fitCameraToObject(camera, controls, root);

  window.addEventListener("resize", () => {
    camera.aspect = container.clientWidth / container.clientHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(container.clientWidth, container.clientHeight);
  });

  // frameCount comes off the wrapper node captureAnimatedScene always
  // stamps with one `frames` entry per baked frame, even a length-1 one for
  // a static export — length>1 is what actually flips this into playback.
  const frameCount = sceneData.frames ? sceneData.frames.length : 1;
  const fps = window.__OVM_FPS__ || 30;
  const startTime = performance.now();

  renderer.setAnimationLoop(() => {
    if (frameCount > 1) {
      const elapsed = (performance.now() - startTime) / 1000;
      const frameIndex = Math.floor(elapsed * fps) % frameCount;
      for (const { object, frames } of animated) {
        const f = frames[frameIndex];
        object.matrix.fromArray(f.matrix);
        object.visible = f.visible;
        // matrixAutoUpdate is off (see buildObject) — mutating .matrix in
        // place doesn't itself mark the object dirty the way updateMatrix()
        // would, so updateMatrixWorld() would keep reusing last frame's
        // cached world matrix without this.
        object.matrixWorldNeedsUpdate = true;
        // Particles: motion lives in the geometry's own position/color, not
        // the object's transform — see sceneSnapshot.ts's SnapshotFrame.
        // position doc. Only present on a Points node whose captured frames
        // actually carried it.
        if (f.position) {
          object.geometry.setAttribute("position", decodeAttribute(f.position));
          if (f.color) object.geometry.setAttribute("color", decodeAttribute(f.color));
        }
      }
    }
    controls.update();
    renderer.render(scene, camera);
  });
}
