import { createRegistry } from "../types";
import { CAMERA_NODE } from "./camera";
import { GRID_NODE } from "./grid";
import { DECOMPOSE_MATRIX_NODE, LOOK_AT_NODE, MATRIX_TRANSFORM_NODE, PARENT_NODE, TRANSFORM_NODE, TRANSFORM_VECTOR_NODE } from "./transform";
import { MAP_RANGE_NODE, VALUE_CONSTANT_NODE, VALUE_MATH_NODE } from "./valueMath";
import { MERGE_NODE } from "./merge";
import { OBJECT_BAR_GRAPH_NODE, OBJECT_BOX_NODE, OBJECT_PLANE_NODE, OBJECT_SPHERE_NODE, OBJECT_TEXT_NODE } from "./object";
import { RENDER_NODE } from "./render";
import { TIME_NODE } from "./time";
import { VECTOR_COMPOSE_NODE, VECTOR_DECOMPOSE_NODE, VECTOR_MATH_NODE } from "./vector";
import { BOOLEAN_LOGIC_NODE, COMPARE_NODE, GATE_NODE, LOGIC_BRIDGE_NODE, TOGGLE_NODE, TRIGGER_NODE } from "./logic";
import { ENVELOPE_NODE, OSCILLATOR_NODE } from "./oscillator";
import { COLOR_COMPOSE_NODE, COLOR_CONSTANT_NODE, COLOR_DECOMPOSE_NODE, COLOR_MATH_NODE } from "./color";
import { COLOR_TO_VECTOR_NODE, VALUE_TO_COLOR_NODE, VALUE_TO_TEXT_NODE, VALUE_TO_VECTOR_NODE, VECTOR_TO_COLOR_NODE } from "./converter";
import { CSV_READER_NODE } from "./csv";
import { COLOR_PALETTE_LIST_NODE, GENERATE_LIST_NODE, GET_LIST_ITEM_NODE, LIST_COMBINE_MATH_NODE, LIST_LENGTH_NODE, LIST_MATH_NODE, LIST_STATISTICS_NODE, SLICE_LIST_NODE } from "./list";
import { INSPECTOR_NODE } from "./inspector";
import { AUDIO_PEAK_DETECTOR_NODE, AUDIO_PLAYER_NODE, AUDIO_SPECTRUM_NODE, AUDIO_SYNTH_NODE, MICROPHONE_INPUT_NODE } from "./sound";
import { RANDOM_LIST_NODE, RANDOM_MATRIX_NODE, RANDOM_VALUE_NODE, RANDOM_VECTOR_NODE } from "./random";
import { KEYBOARD_NODE } from "./keyboard";
import { ARRAY_NODE } from "./array";
import { GET_INSTANCE_NODE, SET_INSTANCE_COLOR_NODE, SET_INSTANCE_TRANSFORM_NODE } from "./instance";
import {
  TEXT_CASE_NODE,
  TEXT_COMPARE_NODE,
  TEXT_CONCAT_NODE,
  TEXT_CONSTANT_NODE,
  TEXT_LENGTH_NODE,
  TEXT_REPLACE_NODE,
  TEXT_SPLIT_NODE,
  TEXT_SUBSTRING_NODE,
  TEXT_TRIM_NODE,
} from "./text";

/** The starter catalogue — grows node by node; BIBLE.md has the full target list. */
export const STARTER_NODES = [
  TIME_NODE,
  VALUE_CONSTANT_NODE,
  VALUE_MATH_NODE,
  MAP_RANGE_NODE,
  VECTOR_COMPOSE_NODE,
  VECTOR_DECOMPOSE_NODE,
  VECTOR_MATH_NODE,
  COLOR_CONSTANT_NODE,
  COLOR_COMPOSE_NODE,
  COLOR_DECOMPOSE_NODE,
  COLOR_MATH_NODE,
  VALUE_TO_VECTOR_NODE,
  COLOR_TO_VECTOR_NODE,
  VECTOR_TO_COLOR_NODE,
  VALUE_TO_COLOR_NODE,
  VALUE_TO_TEXT_NODE,
  TEXT_CONSTANT_NODE,
  TEXT_CONCAT_NODE,
  TEXT_SUBSTRING_NODE,
  TEXT_LENGTH_NODE,
  TEXT_CASE_NODE,
  TEXT_REPLACE_NODE,
  TEXT_SPLIT_NODE,
  TEXT_TRIM_NODE,
  TEXT_COMPARE_NODE,
  TRANSFORM_NODE,
  DECOMPOSE_MATRIX_NODE,
  PARENT_NODE,
  LOOK_AT_NODE,
  MATRIX_TRANSFORM_NODE,
  TRANSFORM_VECTOR_NODE,
  OBJECT_BOX_NODE,
  OBJECT_PLANE_NODE,
  OBJECT_SPHERE_NODE,
  OBJECT_TEXT_NODE,
  OBJECT_BAR_GRAPH_NODE,
  MERGE_NODE,
  ARRAY_NODE,
  SET_INSTANCE_COLOR_NODE,
  SET_INSTANCE_TRANSFORM_NODE,
  GET_INSTANCE_NODE,
  RENDER_NODE,
  COMPARE_NODE,
  BOOLEAN_LOGIC_NODE,
  TRIGGER_NODE,
  TOGGLE_NODE,
  GATE_NODE,
  LOGIC_BRIDGE_NODE,
  KEYBOARD_NODE,
  OSCILLATOR_NODE,
  ENVELOPE_NODE,
  CSV_READER_NODE,
  GET_LIST_ITEM_NODE,
  LIST_LENGTH_NODE,
  GENERATE_LIST_NODE,
  LIST_MATH_NODE,
  LIST_STATISTICS_NODE,
  LIST_COMBINE_MATH_NODE,
  COLOR_PALETTE_LIST_NODE,
  SLICE_LIST_NODE,
  INSPECTOR_NODE,
  AUDIO_PLAYER_NODE,
  AUDIO_SPECTRUM_NODE,
  MICROPHONE_INPUT_NODE,
  AUDIO_PEAK_DETECTOR_NODE,
  AUDIO_SYNTH_NODE,
  RANDOM_VALUE_NODE,
  RANDOM_VECTOR_NODE,
  RANDOM_MATRIX_NODE,
  RANDOM_LIST_NODE,
  CAMERA_NODE,
  GRID_NODE,
];

export const DEFAULT_REGISTRY = createRegistry(STARTER_NODES);

export * from "./time";
export * from "./valueMath";
export * from "./vector";
export * from "./transform";
export * from "./object";
export * from "./render";
export * from "./logic";
export * from "./oscillator";
export * from "./color";
export * from "./converter";
export * from "./merge";
export * from "./csv";
export * from "./list";
export * from "./inspector";
export * from "./sound";
export * from "./random";
export * from "./text";
export * from "./keyboard";
export * from "./array";
export * from "./instance";
export * from "./camera";
export * from "./grid";
